### ISSUE TITLE
Only two marketing spot

### ISSUE THREAD

**Issue by vorfan** [gjb2048/moodle-theme_essential#426]
Is it possible to have only two marketing spots in the front page?

**Comment by vorfan** [comment]
Is it possible to have only two marketing spots in the front page?

**Comment by gjb2048** [comment]
Yes, but requires altering the code: https://github.com/gjb2048/moodle-theme_essential/blob/master/layout/includes/marketingspots.php

**Comment by vorfan** [comment]
Yes I understand that, but what changes do I have to do?
If i delete the code below   and   will be ok?

**Comment by gjb2048** [comment]
Essential is licensed under GPLv3: https://github.com/gjb2048/moodle-theme_essential/blob/master/COPYING.txt#L642-L645 and therefore comes as is with no warranty.
Therefore I'm sorry, but due to excessive demand, I am no longer able to provide bespoke support for specific customisations, I will continue to fix bugs and undertake enhancements when they are funded.
