### ISSUE TITLE
Override pix/bg/header.png

### ISSUE THREAD

**Issue by jcharaoui** [gjb2048/moodle-theme_essential#427]
I'd like to override the header background image in Essential.
Is there an alternative to making a local fork?

**Comment by gjb2048** [comment]
Essential is licensed under GPLv3: https://github.com/gjb2048/moodle-theme_essential/blob/master/COPYING.txt#L642-L645 and therefore comes as is with no warranty.
Therefore I'm sorry, but due to excessive demand, I am no longer able to provide bespoke support for specific customisations, I will continue to fix bugs for no remuneration and undertake enhancements when they are funded.

**Comment by gjb2048** [comment]
You could always ask on the theme's forum: http://moodle.org/mod/forum/view.php?id=46
