### ISSUE TITLE
Custom menu extender button is not working on android Mobile

### ISSUE THREAD

**Issue by knowngate** [gjb2048/moodle-theme_essential#465]
On any android web application with essential theme button on both top corner for custon menu and link icons are not showing when clicked.
It is fine and working in previous vrsion.

**Comment by gjb2048** [comment]
Screen shot please.
What exact version was it working on?
What exact version are you running now?
I do not have an Android device so cannot test.
Is the desktop version ok when you access the site?

**Comment by gjb2048** [comment]
Please also list all third party plugins with their version as there could be a jQuery conflict.

**Comment by knowngate** [comment]
Desktop vrsion is super finr..
But on Android it is not showing custom menus and link icon (website, fb).
I jst setup new 3 moodle site with latest moodle 2.8.3 (build 20150202) and 
essential theme  without any other plugin.
Android kitkat 4.4.4
Firefox browser recently updated.
Yuniverse browser 
chrome browser.

**Comment by knowngate** [comment]
Desktop vrsion is super finr..
But on Android it is not showing custom menus and link icon (website, fb).
I jst setup new 3 moodle site with latest moodle 2.8.3 (build 20150202) and 
essential theme  without any other plugin.
Android kitkat 4.4.4
Firefox browser recently updated.
Yuniverse browser 
chrome browser.

**Comment by knowngate** [comment]
Mistakenly closed..while operatin mobile.
Essential theme vrsion 2.8.1.3 (Build: 2015022700)

**Comment by gjb2048** [comment]
Thanks, but still need...
What exact version was it working on?
Does the 'Clean' theme work?
Browser versions.

I do not have 'Android kitkat 4.4.4' therefore difficult if not impossible to test and replicate.  Unless browser development tools help.

Do you have an idea?

**Comment by knowngate** [comment]
ok .
doing some browser update and collecting some info.
yes for clean theme, it works.
now i m on set-uping moodle system with your theme.
not clear idea now.
i m on testing with new updates.
its fab theme and u doing great job.
i m your fan. :) :+1: 
thanks

**Comment by gjb2048** [comment]
Ok....

Tested on Android 2.2 and fine:

![2015-03-06 09_39_15-android ics running - oracle vm virtualbox](https://cloud.githubusercontent.com/assets/1058419/6523288/4c0cdb2c-c3e6-11e4-9707-2de28e505d68.jpg)

Need to test on Android 4.x... - http://www.sysprobs.com/guide-android-4-4-kitkat-on-pc-virtualbox-windows-7-8

Tested on iOS and fine.

But... could you test this: http://getbootstrap.com/2.3.2/javascript.html#collapse  as jQuery version from the source.  If fail then cannot solve.

**Comment by knowngate** [comment]
Emulator is alwys work fine. On mobile it persist due to low version.

**Comment by gjb2048** [comment]
If the Emulator / Virtual environment is find and the mobile is not then I have no way of replicating and thus fixing.  If the mobile version is 'low' then I recommend updating to current and then retesting.

**Comment by zahrah-** [comment]
Hello,

Did some basic testing on Android 4.1.2 and 4.2.2 with various browsers.
Here is some feedback:

- The button on top left with the menu options works fine. Tested with Android browser, Firefox, Chrome and Dolphin
![android1](https://cloud.githubusercontent.com/assets/8460383/6713253/93c9c922-cd67-11e4-9b26-d1cb73d61fc2.png)
- In portrait mode the social icons do not display but there seems to be an object behind the Log in text on the right. It's difficult to tap on it because you go to the Log in screen.
![android2](https://cloud.githubusercontent.com/assets/8460383/6713147/ea4c9226-cd66-11e4-85b7-253a0840a247.png)
- When on the log in screen it appears a bit more and tapping in that general region reveal the social icons.
![andriod3](https://cloud.githubusercontent.com/assets/8460383/6713179/192f9c46-cd67-11e4-8d5e-4b54daa39778.png)
- see below
![android4](https://cloud.githubusercontent.com/assets/8460383/6713184/1cdff7aa-cd67-11e4-8647-bfe823dd54f8.png)
- In landscape mode on an 8" device everything displays normally.

A similar effect may be seen in Firefox on the PC by making the browser with narrow so it's like mobile mode.

Hope this helps.

**Comment by gjb2048** [comment]
Thanks for the screen shots.

I noticed the 'social icon' collapse button the other day and fixed it for 2.8.1.4 but did not associate this issue with that problem.

**Comment by gjb2048** [comment]
Is this still an issue?

**Comment by zahrah-** [comment]
Sorry for delayed response.
This seems to be fixed on Android with Firefox, Dolphin, Chrome and the Android browser.
Thank you.

**Comment by gjb2048** [comment]
Thanks for getting back to me.
