### ISSUE TITLE
Can I have multiple copies of Essential on the same Moodle Instance?

### ISSUE THREAD

**Issue by gvresearch** [gjb2048/moodle-theme_essential#468]
A client wants to have the Essential theme on their site, but wants to have a couple of different versions of it, customized for each sub-site.  I tried to simply copy and re-name it, but that caused a lot of issues.  Is there a way to do this simply, or do I need to change all of the internal references to "essential" in the code to make it work?

Thanks

**Comment by gjb2048** [comment]
Hi @gvresearch,

Due to continued lack of support for the theme I find myself in the unfortunate position of having to charge for things.  Therefore I'm happy to answer that for a consultancy fee depending on the full description of what you are trying to do.  I.e. one Moodle installation but course themes or many Moodle installations pointing to a common themedir where set at site level only?  What 'sort' of differences in each theme?

Its late here, so I apologise if I don't reply immediately.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
No response in over a month, closing.
