### ISSUE TITLE
Forum grids do not wrap 

### ISSUE THREAD

**Issue by mwcao** [gjb2048/moodle-theme_essential#523]
Hi, 
Thank you for the essential theme. We love it. We use it on our site: journalismcourses.org

But we notice for Portuguese courses, the forum looks like this. But it looks fine in the English ones. 
I think it is because it doesn't wrap when the names get too long. 

![screen shot 2015-08-11 at 2 11 17 pm](https://cloud.githubusercontent.com/assets/5649728/9207656/766de4d6-4034-11e5-862d-a49a4dffe177.png)

![screen shot 2015-08-11 at 2 28 14 pm](https://cloud.githubusercontent.com/assets/5649728/9207774/49560bb2-4035-11e5-8a70-39958ead1f9b.png)

Thank you!

**Comment by gjb2048** [comment]
What version of Moodle / Essential?

**Comment by mwcao** [comment]
Moodle version 2.8
Essential 2.5

**Comment by gjb2048** [comment]
Plus, I've tried to solve this many times, but because the core forum code outputs a table instead of a set of 'div's this is currently impossible to solve elegantly.  Changing word break to 'break-all' just makes it look ugly.

Essential 2.5?

**Comment by mwcao** [comment]
I was looking at the readme.txt 
Yeah we are using Essntial 2.5

We are in the middle of a course so we don't really want to upgrade. 

Do you have any suggestions? Is it because the names are too long?

**Comment by gjb2048** [comment]
I only ever support the latest version for a given branch, so for M2.8 that is: 2.8.1.7 (Build: 2015061901).  This is because it would then be supporting so many different versions at different times.  I'm happy to fix issues in the current version, but going back is beyond the call of duty.  Especially here as the code is so out of date and things have progressed a long way since then.  If you want support, then please try the theme's forum or consider paying me to look into it.

**Comment by mwcao** [comment]
I understand. Do you know if this problem is solved in the current version? We will upgrade if it is solved.

**Comment by gjb2048** [comment]
No I don't.

**Comment by gjb2048** [comment]
Happens in M2.8.1.7: 

![Uploading 2015-08-13 16_56_01-News forum.jpg…]()

**Comment by gjb2048** [comment]
.path-mod-forum .forumheaderlist td {
  padding: 5px;
  word-break: break-all; /* FireFox */
  word-break: break-word; /* Chrome */
  &:last-of-type {
    border-right-width: 1px;
  }
}

Seems to fix it.
