### ISSUE TITLE
Divider does not show.

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#529]
Ref to solution for #527 - whilst the hashes are removed, the divider itself does not show up.  M2.8 and M2.9 issue.

**Comment by lazydaisy** [comment]
Have you altered any code for the custommenu?

**Comment by gjb2048** [comment]
Only in terms of actually making the code work in terms of: https://github.com/gjb2048/moodle-theme_essential/commit/925ef042c105336b9f982abf8e21c432e25962b8#diff-492783807c33850a258efa189c59b5b2R180 - which is adapted from core Mary.  Previously the divider 'li' was not even injected into the markup!

**Comment by lazydaisy** [comment]
Are you talking about Desktop view or when on smaller screens?  If the latter then the divider changes from vertical to horizontal. I added the CSS for that in Bootstrapbase a few weeks back.

**Comment by gjb2048** [comment]
Smaller screens, desktop view is horizontal.  Saw: https://tracker.moodle.org/browse/MDL-50533

**Comment by lazydaisy** [comment]
https://github.com/lazydaisy/moodle/commit/0163c590f3c31da7dcada9a541a02fe9892b400b

**Comment by lazydaisy** [comment]
so have you got this fixed in Essential yet?

**Comment by gjb2048** [comment]
Yes: https://github.com/gjb2048/moodle-theme_essential/blob/MOODLE_28/less/moodle/responsive.less#L444-L451

**Comment by gjb2048** [comment]
M2.9: https://github.com/gjb2048/moodle-theme_essential/commit/c59c8fa3b491888443af899b9c281f33d236dc88

**Comment by gjb2048** [comment]
M2.8: https://github.com/gjb2048/moodle-theme_essential/commit/896d667be88ff89b7f6d00795137b2acf14b97e4

**Comment by gjb2048** [comment]
M2.8: https://github.com/gjb2048/moodle-theme_essential/commit/c6b5ea80ae9094b859a4084c8c1866dc3d1adfe6

**Comment by lazydaisy** [comment]
Thanks for this info...

Changing subject...
I have added you as a watcher here...

https://tracker.moodle.org/browse/MDL-48947

I'm not sure but they might be using your ideas from Coll Topic course format...but I may be wrong...It's a long discussion...and an on iPad and find it hard to read...but thought you might like to see what's going on all the same.

It's in integration review now...
I only got to know about it because Fred Massart mentioned me in the discussion...about hidden blocks a z-index + opacity conundrum.

Cheers
Mary

**Comment by gjb2048** [comment]
Thanks for the info Mary :)
