### ISSUE TITLE
Admins should always see "additional front page middle blocks" when editing is turned on

### ISSUE THREAD

**Issue by andreumarti** [gjb2048/moodle-theme_essential#603]
Hi Gareth!

In the Front page settings we have the setting: "theme_essential | frontpagemiddleblocks" set to "Show before login only".

Every time, as an admin, I need to perform changes to those blocks, I have to change the above setting to "Always show" or "Show after login only" and therefore any other logged user also see the blocks during that period of time.

It would be nice if the "additional front page middle blocks" could be visible by the admins (when editing is turned on) regardless the setting chosen in the field: "theme_essential | frontpagemiddleblocks"

Is that possible?

Andreu.-

**Comment by gjb2048** [comment]
Hi Andreu,

Yes that is possible and makes sense.  Any fix I make will only be in M2.9 and M3.0 versions.

Gareth

**Comment by gjb2048** [comment]
Logic bug where the original implementation should have thought of this scenario.

Probably going to go with 'editing on' as only check so that anybody who core thinks can edit the page can alter the blocks.

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/0f0265bf858df7c91985ab7eb343a2e7ad018bb5 - logic applies elsewhere too.

Logic is that if not 'Never show' then will appear on frontpage if editing is on and thus the user could change the content - possibly - need to see if need an 'is_admin' guard too.
