### ISSUE TITLE
Custom category icon images

### ISSUE THREAD

**Issue by gjb2048** [gjb2048/moodle-theme_essential#622]
Ref: https://moodle.org/mod/forum/discuss.php?d=328439#p1321905

Allow the user to upload images instead of the icon for a category icon.  Would complement existing functionality.

Cost estimate with testing and checking did not break existing icon functionality: 1 - 1.5 days.

**Comment by ryankuhne** [comment]
How much would 1.5 days cost and how would we move forward on this. 
Thank you!

**Comment by gjb2048** [comment]
My rates have just gone up.  1.5 days = 351.25 GBP.  Quote valid for 30 calendar days.  I can send you full terms of business to an eMail address.

**Comment by gemguardian** [comment]
Hi Gareth,
I have some that is interested in this idea to upload images instead of using font-awesom icons. Is the qoute still the same or adjusted? Please let me know. 

Not sure if Ryan is still interested in this feature, if so we would might be able to split the costs? 

thank you 
Gem

**Comment by gjb2048** [comment]
Hi Gemma,

My rates have not changed since the quote.  Therefore still 1.5 days = 351.25 GBP. Quote valid for 30 calendar days as of today 22nd March 2017.

Kind regards,

Gareth

**Comment by gemguardian** [comment]
Hi Gareth, 

 

I want to be too able to upload images instead of using fa-icons at Essential > Categorie Icons settings. 

 

This feature would be for me to use in Moodle 3.1, 3.2 and of course when available 3.3 
I have no need for the change in earlier Moodle versions. 


You know my billing address 😊 

 

Thank you again for all your great work. 

 

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: woensdag 22 maart 2017 13:21
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] Custom category icon images (#622)

 

Hi Gemma,

My rates have not changed since the quote. Therefore still 1.5 days = 351.25 GBP. Quote valid for 30 calendar days as of today 22nd March 2017.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
Hi Gemma,

I'm going to start on this by developing in a separate M3.2 version branch, then back/forward port to M3.1 / M3.3.

G
