### ISSUE TITLE
Course content search dialog does not show up properly on RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#628]
![image](https://cloud.githubusercontent.com/assets/231168/13536019/1aab42a6-e246-11e5-80b9-d3e79b3a1fe3.png)

**Comment by gjb2048** [comment]
Umm, in what way?  Its aligned on the right and the text is on the right.  The site administration search box works in the same way language wise.

**Comment by gjb2048** [comment]
Ok, the words 'Course content' have not been translated, but that's an AMOS language pack issue.

**Comment by gjb2048** [comment]
Oh, ok, the drop down is in the wrong place.  Not sure what to do about this as jQuery auto-complete calculates the position of this.

**Comment by gjb2048** [comment]
This: http://api.jqueryui.com/autocomplete/#option-position does not seem to help.

**Comment by nadavkav** [comment]
Sorry for not mentioning the drop down, I thought the screen capture was clear.
Indeed a jquery issue.
Maybe I can override it with some !important selectors ;-)

**Comment by gjb2048** [comment]
Hi Nadav,

I spent two hours looking at this last night.  I think the jQueryUI code is at fault.  The markup it has for the list is placed elsewhere, making it difficult in CSS to address the issue.  Perhaps instead of using the whole of jQueryUI there needs to be another JS module for this.  One such one is Twitter Typeahead (https://twitter.github.io/typeahead.js/) which is in BS2 but not 3.  The BS2 version is bugging according to Mark Odo and thus was dropped in BS3 as the Twitter version is better with more features.  However, it needs modification for BS3 (and I want to keep the same code for Shoehorn and if Essential ever moves to BS3+) styles wise.  Plus I need to learn the new API and see if it does everything it needs to do along with being fine on RTL - hoping for a quick test.  This is not going to be a short fix.  I'll probably fix Shoehorn first.

G

**Comment by gjb2048** [comment]
Does this: https://twitter.github.io/typeahead.js/examples/#rtl-support work for you?

**Comment by nadavkav** [comment]
Thank you for diving deep into this! I also played with your previous "option-position" suggestion with not success. It seems like a jQueryUI issue.
Your last suggestion (rtl-support) works fine. Can this be used?

**Comment by gjb2048** [comment]
Maybe, as I said, a lot of work as its a whole new JS module.

**Comment by nadavkav** [comment]
Please, do not continue to work on this. as it is a minor issue. at least for now. (Thanks!)

**Comment by gjb2048** [comment]
But it is a bug and once it has been seen it cannot be 'unseen'.

**Comment by nadavkav** [comment]
You made me :smile: 
(just put it on a low priority)

**Comment by gjb2048** [comment]
Umm, no!  You made me by raising the issue in the first place! ;)

**Comment by nadavkav** [comment]
Super Cool
