### ISSUE TITLE
Problem with popup in quiz with timer.

### ISSUE THREAD

**Issue by tunalkan** [gjb2048/moodle-theme_essential#663]
In a quiz programed with timer in alert popup don't show button for cancel or enter in quiz under alert text.
In moodle 3.1
![screen](https://cloud.githubusercontent.com/assets/19637664/15635454/cf143052-259b-11e6-83b0-6209c05016c1.jpg)

**Comment by tunalkan** [comment]
Hi my friend.
Is it possible to solve this problem? If not fixed, I have to replace the essential theme for another because we can not use the timer.
Thank

**Comment by gjb2048** [comment]
Yes it will be possible to solve the problem when I make a version of Essential for Moodle 3.1.

**Comment by tunalkan** [comment]
Okay. Thank you.
You can accelerate this version?
I can help with some payment

**Comment by gjb2048** [comment]
Hi,

I'm working on a crowdfunding this version.  This will be around 250GBP.

Kind regards,

Gareth

**Comment by tunalkan** [comment]
How I am part of this payment?
Should I pay all that money?

**Comment by gjb2048** [comment]
Ok, right:

At the moment I do not know how long the job will take, I do know it will take at least a day - hence the 250 GBP for crowdfunding and bug fixing.  However, that is the crowdfunding cost that I'm working on setting up on MoodleGarage as with the M3.0 version.  But that would not expedite things and indeed still not solve this problem which may or may not be fixed by this process and could be a separate issue by which I spend more time after that.

Given the bespoke nature of the upgrade I cannot say exactly how long it will take as I'm going to undertake a change this time from the M3.0 version whereby it will be easier to maintain in the future.  Thus, probably between 1 and 3 days but could be more.

I will announce the crowd-funding solution as soon as I've got it worked out.  If you want it expedited then that's a different rate and I'd want paying for all my time.  Thus could be a four figure sum in GBP.

Kind regards,

Gareth

**Comment by gjb2048** [comment]
P.S. Pragmatically I don't really want to rush this but get it right.

**Comment by jk3us** [comment]
FYI, I've found that commenting out 

    $THEME->plugins_exclude_sheets = array('mod' => array('quiz'));

in essential's config.php "fixes" this problem.  I'm sure there are other side effects, but so far this workaround seems to make everything work.  The rule in `mod/quiz/style.css` that is needed to not hide those buttons is:

```
/* Standard Moodle rule that needs to be more specific here. */
.moodle-dialogue-bd #mod_quiz_preflight_form fieldset.hidden {
    display: inherit;
    visibility: inherit;
}
```

**Comment by tunalkan** [comment]
Sorry jk3us, this don't fix the problem.
How is ??

Thank

**Comment by jk3us** [comment]
I think you need to purge your moodle caches to have this change take effect.  See Site Administration -> Development -> Purge all caches.

**Comment by tunalkan** [comment]
Thankyouuuuuu:
I had not thought in the cache

Very good jk3us

Hopefully now it is resolved in the next version

**Comment by tunalkan** [comment]
Gareth, I hope your crowdfunding to participate

Kind regards,

Suso

**Comment by gjb2048** [comment]
Thank you Suso, news soon I hope, cheers, Gareth

**Comment by gjb2048** [comment]
Hi Suso,

I cannot find the option on the Quiz to have the timer in a pop-up, where is it please?

Gareth

**Comment by tunalkan** [comment]
![1](https://cloud.githubusercontent.com/assets/19637664/16051693/048f7af0-321e-11e6-8e65-04880e7c2d2d.jpg)

**Comment by tunalkan** [comment]
![2](https://cloud.githubusercontent.com/assets/19637664/16051700/0cd53790-321e-11e6-9f3d-ccd9f27d9221.jpg)

**Comment by gjb2048** [comment]
Thanks Suso, found it!

Cannot replicate in development version:

![2016-06-14 17_50_33-tp_ a quiz](https://cloud.githubusercontent.com/assets/1058419/16051732/d2534f2c-3258-11e6-9919-878d6be9a60d.png)

**Comment by tunalkan** [comment]
![3](https://cloud.githubusercontent.com/assets/19637664/16051740/3a364878-321e-11e6-96fb-01f75a4d4eeb.jpg)

**Comment by gjb2048** [comment]
Development branch: https://github.com/gjb2048/moodle-theme_essential/tree/master_bsb - NOT for production - completely fluid and prone to combined commits / rebasing etc.

**Comment by tunalkan** [comment]
Sorry, I don't understand ¿?
What is it?

**Comment by gjb2048** [comment]
The development branch I'm using to make the M3.1 version of the theme which does not have the problem.

**Comment by tunalkan** [comment]
ah. Ok. 
The development branch I'm using to make the M3.1 version of the theme which does not have the problem.

**Comment by gjb2048** [comment]
Well sort of, the development branch I am using to make the M3.1 version of the theme.
