### ISSUE TITLE
Fix alignment in course user enrollment dialog, when in RTL mode

### ISSUE THREAD

**Issue by nadavkav** [gjb2048/moodle-theme_essential#689]
![image](https://cloud.githubusercontent.com/assets/231168/16700341/2ab4bb1c-4562-11e6-80f1-874ec4e1001d.png)
And fix:
```
.dir-rtl .user-enroller-panel .uep-search-results .user .count {
    float: right;
}
.dir-rtl .user-enroller-panel .uep-search-results .user .picture {
    float: right;
}
.dir-rtl .user-enroller-panel .uep-search-results .user .details {
    float: right;
}
.dir-rtl .user-enroller-panel .uep-search-results .user .options .enrol {
    float: left;
}
```
Would probably look better if I used LESS :wink:

**Comment by gjb2048** [comment]
Bug in Clean theme too:

![2016-07-08 22_03_46-topics_ 2](https://cloud.githubusercontent.com/assets/1058419/16701498/068b70c8-4558-11e6-992f-01d40638f05d.png)

Thus as Essential now inherits from Bootstrapbase then there is no point in fixing Essential.  When fixed in core would only then have to remove fix in Essential.  Please raise a core issue on the Moodle tracker Nadav.

**Comment by nadavkav** [comment]
Indeed.
Here is a link to a new tracker issue: [MDL-55170](https://tracker.moodle.org/browse/MDL-55170)

**Comment by nadavkav** [comment]
Probably my fault it was missed. as I was (am) for most of the rtl fixes in core :cry:

**Comment by gjb2048** [comment]
Peer reviewer missed it - see last bullet on: https://docs.moodle.org/dev/Peer_reviewing#Output

**Comment by gjb2048** [comment]
And therefore the integrator too.

**Comment by nadavkav** [comment]
Still, my fault :smile: 
btw, a more elegant LESS fix:
https://github.com/moodle/moodle/compare/master...nadavkav:MDL-55170_master
