### ISSUE TITLE
3 block regions displaying in Edit mode for a 2-column layout

### ISSUE THREAD

**Issue by zahrah-** [gjb2048/moodle-theme_essential#751]
Hello Gareth,

It's been a while, I hope all's well on your end.

I've recently upgraded to:
Moodle 3.1.2 (Build: 20160912)
Essential 3.1.0.8 (Build: 2016061707)

Today when I turned on Edit mode my main block is being compressed to make space for a third column when there are only 2 columns on my course page. This makes it somewhat difficult for editing. 
See following screenshots:
 
![xtrablock1](https://cloud.githubusercontent.com/assets/8460383/18608283/35ff7e66-7cb3-11e6-8845-5ca1b056500f.png)
 
![xtrablock2](https://cloud.githubusercontent.com/assets/8460383/18608287/57c9d460-7cb3-11e6-932e-9fa2b1cbdac4.png)
 
![xtrablock3](https://cloud.githubusercontent.com/assets/8460383/18608289/5dcd2a24-7cb3-11e6-8d98-92e6b2255118.png)
 
![xtrablock4](https://cloud.githubusercontent.com/assets/8460383/18608291/634ac74a-7cb3-11e6-921d-078c60661201.png)
 
I've checked the closed issues to see if there's any fix but didn't see anything directly related to the layout change in Edit mode.

If you need any further info let me know.

Thank You.

**Comment by gjb2048** [comment]
I'm good thank you.

Courses are a three column layout.  When editing is on, both of the block regions appear.  It used to be that empty columns only appeared when drag and drop, however I changed that because of needing to show where the region was even if empty as blocks can be told where to go.

Need to think.

**Comment by gemguardian** [comment]
Hi Gareth,

I got the same comment from Petra. She has the upgrade now in her Moodle 2.9 site and she said that before the content page didn't push to the left. She finds it very confusing since all her content now shows in a small area on the left, and that consist alot of scrolling. 

Maybe I am off track, but I though there has been an option in Essential that you could say you wanted the content to show left or right - or maybe I am just confused with a different theme. 

I have enclosed a picture of her screen - so you can see what happens for her. She is using Grid as a courseformat. 
![prtscrn blokken](https://cloud.githubusercontent.com/assets/16559999/19146619/89c51848-8bb4-11e6-83a7-cabd94f3c95d.png)

**Comment by gjb2048** [comment]
Hi Gemma,

There is the 'layout' setting which means that it will revert to the block, content, block layout.  However, given the description that would not solve the content / scrolling issue.

I think I need to change the complicated logic that the outline box does not appear for a region when empty and only when drag / drop or it has blocks.

G

**Comment by gemguardian** [comment]
Hi gareth,

 

I have tried that setting – or at least I think you mean the setting to use the “orginal” layout. 
And that doesn’t work indeed. 

 

Goodluck!

 

Gemma 

 

Van: Gareth J Barnard [mailto:notifications@github.com] 
Verzonden: donderdag 6 oktober 2016 16:03
Aan: gjb2048/moodle-theme_essential <moodle-theme_essential@noreply.github.com>
CC: gemguardian <gemma@ltnc.nl>; Comment <comment@noreply.github.com>
Onderwerp: Re: [gjb2048/moodle-theme_essential] 3 block regions displaying in Edit mode for a 2-column layout (#751)

 

Hi Gemma,

There is the 'layout' setting which means that it will revert to the block, content, block layout. However, given the description that would not solve the content / scrolling issue.

I think I need to change the complicated logic that the outline box does not appear for a region when empty and only when drag / drop or it has blocks.

G

**Comment by gjb2048** [comment]
Fixed in https://github.com/gjb2048/moodle-theme_essential/commit/02f8e8509a59676aa6d0fa408f2bbb5bc5c71fe1

**Comment by zahrah-** [comment]
Thank you!
