### ISSUE TITLE
Rendering problem in quiz form

### ISSUE THREAD

**Issue by Balecan** [gjb2048/moodle-theme_essential#860]
Input width breaks readability
![essential02](https://user-images.githubusercontent.com/11347832/36299774-eb92b6c0-12fe-11e8-8815-d4d9b092b6b6.png)

with default theme :
![basic](https://user-images.githubusercontent.com/11347832/36299779-f1be8b96-12fe-11e8-82f0-bcff56c749aa.png)

Best regards

**Comment by gjb2048** [comment]
Thanks for the patch, but given the solution of removing:

-fieldset textarea[cols],
-fieldset input[size] {
-  width: 65.95744681%;
-  *width: 65.90425532%;
-}

then:

- What are the implications of this on other forms like the course settings etc.  Please provide evidence that they are not broken.
- Update and compress the patch into one commit so that the LESS source is also changed to reflect the CSS change as the later is just the output from the Grunt LESS compiler.

**Comment by Balecan** [comment]
I don't know grunt & less but i tried...
After several tries i've succefully installed nodejs and grunt on my debian stretch but now i have this errors 
pc-gt% ./node_modules/grunt-cli/bin/grunt css
Running "less:essential_d" (less) task
>> FileError: '../../bootstrapbase/less/bootstrap/variables.less' wasn't found. Tried - ../bootstrapbase/less/bootstrap/variables.less,../bootstrapbase/less/bootstrap/variables.less,../../bootstrapbase/less/bootstrap/variables.less in less/essential.less on line 16, column 1:
>> 15 // Import the bootstrap variables.
>> 16 @import "../../bootstrapbase/less/bootstrap/variables.less"

I miss some basics and time to go further
Sorry

**Comment by gjb2048** [comment]
Did you follow the instructions in https://github.com/gjb2048/moodle-theme_essential/blob/master/Gruntfile.js and run in the essential folder?

**Comment by gjb2048** [comment]
Any progress please?

**Comment by gjb2048** [comment]
Note screen shot is from "Adding a short answer question" when adding that type of question to a quiz.
