### ISSUE TITLE
Login token support (3.1.15, 3.3.9, 3.4.6, 3.5.3, 3.6)

### ISSUE THREAD

**Issue by otatarintseva** [gjb2048/moodle-theme_essential#880]
The changes to the login process in Moodle versions 3.1.15, 3.3.9, 3.4.6, 3.5.3, 3.6 require a fix to the header login, if enabled.

Without this patch, the top login will fail due to missing token.

For details of required changes, see: https://docs.moodle.org/dev/Login_token

**Comment by gjb2048** [comment]
Thanks for the information but I already know all about this and have checked the theme.  It is not affected.

**Comment by UncleRaymondo** [comment]
Can we please reopen this as it is affected... I've just had to use the disablelogintoken workaround for users to be able to login using this theme.

Cheers,
Ray

**Comment by gjb2048** [comment]
Dear Ray,

I don't know why you keep asking this as the theme ALREADY SUPPORTS THE LOGIN TOKEN!!!!!

I've already checked the Moodle 3.5 version and have just double checked the versions for Moodle 3.3 and 3.4. Any version less than that is unsupported but I doubt that there would be a problem due to the nature of the issue.

Please post here clear evidence that it is actually the Essential theme with the issue.

Gareth
